#!/bin/sh 

# Might update this later to env


# TODOs 
# find ~ -type f -mtime 0
# mtime 0 means last 24 hours 1 means 24-48 hours 
# Update to include more and then use args to refine what you are looking for?

rootdir='/'
exclude='container|cache|.git/objects' # Adding .git objects these look to change very frequently with trees and commits
include='^/(home|etc|dev)'

find "$rootdir" -mtime 0 -type f 2>/dev/null | grep -E "$include" | grep -E -v "$exclude"

