#!/bin/sh 

# Might update this later to env


# TODOs 
# use find to get all files that have changed since a specific time
# Automation
# eliminate files that we don't care about (this goes second)
# Further refinement of include
# changes to specific include (maybe pass in prompt)
# find ~ -type f -mtime 0
# mtime 0 means last 24 hours 1 means 24-48 hours 

rootdir='/'
exclude='container|cache'
include='^/(home|etc|dev)'

find "$rootdir" -mtime 0 -type f 2>/dev/null | grep -E "$include" | grep -E -v "$exclude"

